name       : perl-sub-exporter-progressive
version    : 0.001013
release    : 8
source     :
    - http://search.cpan.org/CPAN/authors/id/F/FR/FREW/Sub-Exporter-Progressive-0.001013.tar.gz : d535b7954d64da1ac1305b1fadf98202769e3599376854b2ced90c382beac056
license    : Artistic-2.0
component  : programming.perl
summary    : Sub Exporter Wrapper
description: |
    Sub::Exporter is an incredibly powerful module, but with that power comes great responsibility, er- as well as some runtime penalties. This module is a Sub::Exporter wrapper that will let your users just use Exporter if all they are doing is picking exports, but use Sub::Exporter if your users try to use Sub::Exporter's more advanced features, like renaming exports, if they try to use them.
rundeps    :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
